title: Ione Souza Junior
role: Mobile Engineer
description: Ione Souza Junior - Mobile Engineer

url: https://ionixjunior.dev
paginate_path: "page:num/"
permalink: :title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-target-blank
paginate: 5

navigation:
    - title: Início
      url: /index.html
    - title: Sobre
      url: /about

social:
    github: ionixjunior
    twitter: ionixjunior
    linkedin: ionixjunior

google_analytics: "G-G7JHVXT0LV"

# disqus:
#     shortname: brianmaierjr
