title: Ione Souza Junior
role: Mobile Engineer
description: Ione Souza Junior - Mobile Engineer

url: https://ionixjunior.dev
paginate_path: "page:num/"
permalink: :title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-target-blank
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin
paginate: 5

navigation:
    - title: menu.home
      url: /index.html
    - title: menu.about
      url: /about

social:
    github: ionixjunior
    twitter: ionixjunior
    linkedin: ionixjunior

google_analytics: "G-3GS0413SHR"

languages: ["pt", "en"]

# disqus:
#     shortname: brianmaierjr
