title: Ione Souza Junior
role: Mobile Engineer
description: Ione Souza Junior - Mobile Engineer

url: https://ionixjunior.dev
paginate_path: "post/page:num/"
permalink: post/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about

social:
    github: ionixjunior
    twitter: ionixjunior
    linkedin: ionixjunior

google_analytics: "G-G7JHVXT0LV"

# disqus:
#     shortname: brianmaierjr
