services:
  hugo:
    image: hugomods/hugo:latest
    container_name: ionixjunior_dev
    ports:
      - "1313:1313"
    volumes:
      - ./src:/src
    command: server --bind 0.0.0.0 --baseURL=http://localhost:1313
