title: Ione Souza Junior
role: Mobile Engineer
description: Ione Souza Junior - Mobile Engineer

url: https://ionixjunior.dev
paginate_path: "page:num/"
permalink: :title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-target-blank
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin
paginate: 5

navigation:
    - title: menu.home
      url: /index.html
    - title: menu.about
      url: /about

social:
    github: ionixjunior
    twitter: ionixjunior
    linkedin: ionixjunior

google_analytics: "G-G7JHVXT0LV"

languages: ["pt", "en"]

exclude:
  - script.sh
  - cards_downloader.sh
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
  - preview.jpg
  - preview-dark.png
  - preview-large.png

# disqus:
#     shortname: brianmaierjr
