baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My New Hugo Site"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.pt]
    languageName = "Português"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true